POST http://localhost:8000/api/poli
Content-Type: application/json

{
    "PoliName":"Poli A",
    "PoliCode":"P - A",
    "PoliColor":"255,0,255"
}

###
GET http://localhost:8000/api/poli?search=

###
GET http://localhost:8000/api/poli/queue

###
PUT http://localhost:8000/api/poli/6822d5ffb82d26757adc5964
Content-Type: application/json

{
    "PoliName":"Poli Second",
    "PoliCode":"P - 2",
    "PoliColor":"0,0,0"
}

###
DELETE http://localhost:8000/api/poli/68236129075474b86c44e8d7

###
PUT http://localhost:8000/api/poli/print-queue/6822e7dc191c0427ab4b39a8

###
PUT http://localhost:8000/api/poli/ring-queue/6822d58f90248647c402716d
Content-Type: application/json

{
    "No":1,
    "Date":"2025-05-13"
}
